name: Alimentation schema ONCDOS

on:
  push:
    branches:
      - patient_osiris

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy DAGs to Airflow
        run: |
          set -e

          TARGET="$HOME/airflow/dags/osiris_rwd"
          mkdir -p "$TARGET"

          echo "Deploying DAGs to $TARGET"

          # rsync synchronise et supprime les fichiers obsolètes
          rsync -av --delete ./ "$TARGET/"

          echo "Deployment finished"
